name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: |
        cd backend
        npm install
        cd ../frontend
        npm install
    - name: Run Backend Tests
      run: |
        cd backend
        npm test
    - name: Run Frontend Tests
      run: |
        cd frontend
        npm test
